-- Supabase setup for lessons/company engagement platform
-- Safe to run in the SQL editor of your Supabase project.

create table if not exists public.content_reactions (
  id bigint generated by default as identity primary key,
  site_key text not null,
  content_id text not null,
  visitor_id text not null,
  reaction_type text not null default 'like',
  created_at timestamptz not null default timezone('utc', now())
);

create unique index if not exists content_reactions_unique_like
  on public.content_reactions (site_key, content_id, visitor_id, reaction_type);

create index if not exists content_reactions_lookup_idx
  on public.content_reactions (site_key, content_id, reaction_type);

grant usage on schema public to anon;
grant select, insert, update, delete on public.content_reactions to anon;
grant usage, select on sequence public.content_reactions_id_seq to anon;

alter table public.content_reactions enable row level security;

drop policy if exists "Public can read reactions" on public.content_reactions;
create policy "Public can read reactions"
  on public.content_reactions
  for select
  using (true);

drop policy if exists "Public can insert reactions" on public.content_reactions;
create policy "Public can insert reactions"
  on public.content_reactions
  for insert
  with check (reaction_type = 'like');

drop policy if exists "Public can delete own reactions" on public.content_reactions;
create policy "Public can delete own reactions"
  on public.content_reactions
  for delete
  using (reaction_type = 'like');

comment on table public.content_reactions is 'Shared reactions table for lessons and future company site content.';
comment on column public.content_reactions.site_key is 'Logical site identifier, e.g. lessons or company.';
comment on column public.content_reactions.content_id is 'Stable content identifier that survives title/file changes.';
comment on column public.content_reactions.visitor_id is 'Browser-local UUID used to prevent duplicate likes per visitor.';